# This file contains new (to us) RuboCop rules which have yet to be implemented.
# When time permits, consider creating a branch to enable one or more of these
# rules and update our codebase to pass.


# This rule can be implemented automatically, but it's a large diff.
Layout/HashAlignment: { Enabled: false }

# As-is we align method calls on a case-by-base basis. If the results aren't too
# ugly, it may be better to implement this rule.
Layout/MultilineMethodCallIndentation: { Enabled: false }

# This rule is only disabled because there are currently too many violations.
# see http://wiki.c2.com/?AbcMetric
Metrics/AbcSize: { Enabled: false }

# This rule is only disabled because there are currently too many violations.
Metrics/BlockLength: { Enabled: false }

# This rule is only disabled because there are currently too many
# violations. This rule can't be automatically fixed, but it can be fixed by
# hand without much thought. You only need to nest inside module blocks, instead
# of Module::Class style.
Style/ClassAndModuleChildren: { Enabled: false }

# This rule is only disabled because there are currently too many violations. It
# would be nice to be able to enable this one though, as many other RuboCop
# rules use this rule for their automatic-formatting feature.
Layout/LineLength: { Enabled: false }

# This rule is only disabled because there are currently too many violations.
Metrics/MethodLength: { Enabled: false }

# Decide whether we ever want to implement this particular rule. It requires all
# exception variables to be named "e".
Naming/RescuedExceptionsVariableName: { Enabled: false }

# This rule is only disabled because there are currently too many violations.
Rails/HasManyOrHasOneDependent: { Enabled: false }

# This is probably a good rule to implement and we only have these few
# helpers which currently violate it.
Rails/HelperInstanceVariable:
  Exclude:

################################################################################
# "Grandfathered" Exceptions
#
# This section contains exceptions for certain, older files. For the most part,
# these are the files which violated some rules so badly when we began to use
# RuboCop that there wasn't time to fix them. Someday a hero will come and make
# these files compiant, so they can be removed from these lists.
#
# You may add new entries here, but please an aproriate amount of shame when
# doing so.
################################################################################
Metrics/ClassLength:
  # These "grandfathered" classes can be refactored on a case-by-case basis
  Max: 250
  Exclude:

Metrics/CyclomaticComplexity:
    Max: 10
    Exclude:

Metrics/ModuleLength:
  Exclude:

Metrics/PerceivedComplexity:
  Exclude:

Rails/HasAndBelongsToMany:
  Exclude:
