require: rubocop-rails

# This file contains rule exceptions that we want to fix eventually.
inherit_from: .rubocop_todo.yml


AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*" # for Circle CI's benefit

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def
  AutoCorrect: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

# Warns when you override a default Struct method. Little use.
Lint/StructNewOverride:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - "app/exporters/**/*"
    - "app/helpers/**/*"
    - "app/mailers/**/*"
    - "app/workers/**/*"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - "config/deploy.rb"
    - "lib/data_populator.rb"

# We have rake tasks that do not require Rails to be loaded.
Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"

Rails/UnknownEnv:
  Environments:
    - demo
    - development
    - production
    - sandbox
    - staging
    - test
    - testing

# Currently, we prefer to use less documentation than RuboCop suggests.
Style/Documentation: { Enabled: false }

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

# Different situations call for different format strings. Requiring
# the same style in all cases is too restrictive.
Style/FormatStringToken: { Enabled: false }

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# With Metrics/LineLength disabled, this rule requires very long lines.
Style/IfUnlessModifier: { Enabled: false }

# It's convenient to write cents literals (ie: money) as 1234_99
Style/NumericLiterals:
  Exclude:
    - "spec/**/*"

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
